spring.application.name=webserver
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xjrufgxhrzuzzaoooapg
spring.datasource.password=Mile$$oo&&((
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
